# Generated by Django 4.2.5 on 2023-11-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Categoria')),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT/Cuil')),
                ('localidad', models.CharField(max_length=250, verbose_name='Localidad')),
                ('baja_proveedor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=50, verbose_name='Artículo')),
                ('imagen', models.ImageField(blank=True, max_length=250, null=True, upload_to='img', verbose_name='Imagen')),
                ('precio', models.CharField(max_length=25, verbose_name='Precio')),
                ('marca', models.CharField(max_length=25, verbose_name='Marca')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.categoria')),
                ('proveedor', models.ManyToManyField(to='gerencia.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerencia.producto')),
            ],
            options={
                'db_table': 'Detalle de Pedido',
            },
        ),
    ]
